spring.application.name=laperuanita

# ================================
# SERVIDOR
# ================================
server.port=8081

# ================================
# BASE DE DATOS - PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5434/laperuanita_db
spring.datasource.username=postgres
spring.datasource.password=laperuanita2024
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ================================
# LOGS
# ================================
logging.level.com.emersondev=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT
jwt.secret=laperuanita-secret-key-muy-larga-para-que-sea-segura-2024-emersondev
jwt.expiration=86400000

# Zona Horaria del servidor
spring.jackson.time-zone=America/Lima
server.timezone=America/Lima


#
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true

# ================================
# APIS EXTERNAS
# ================================
apisnetpe.url=https://api.decolecta.com/v1/reniec/dni
apisnetpe.token=sk_16397.VdMVAC8jc1Ow1VuSZRGaXxwVdPdO9sr0
