spring.application.name=impor.denraf

# ================================
# BASE DE DATOS - PostgreSQL
# ================================
spring.datasource.url=jdbc:postgresql://localhost:5433/denraf_db
spring.datasource.username=postgres
spring.datasource.password=denraf2024
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ================================
# LOGS
# ================================
logging.level.com.emersondev=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT
jwt.secret=denraf-secret-key-muy-larga-para-que-sea-segura-2024-emersondev
jwt.expiration=86400000

# Zona Horaria del servidor
spring.jackson.time-zone=America/Lima
server.timezone=America/Lima


#
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true
